/*

 BLANKSCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\barry\Desktop\Creating stuffs\Game Dev\GB development\Cell Machine GB\cells.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define blankscreenWidth 20
#define blankscreenHeight 18
#define blankscreenBank 0

extern unsigned char blankscreen[];

/* End of BLANKSCREEN.H */
